services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: serviceflow-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "14333:1433"
    volumes:
      - serviceflow_sqlserver_data:/var/opt/mssql
    restart: 
      unless-stopped

volumes:
  serviceflow_sqlserver_data: